//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PakMua
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_rentalanEntities : DbContext
    {
        public db_rentalanEntities()
            : base("name=db_rentalanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tb_member> tb_member { get; set; }
        public virtual DbSet<tb_mobil> tb_mobil { get; set; }
        public virtual DbSet<tb_order> tb_order { get; set; }
        public virtual DbSet<tb_order_mobil> tb_order_mobil { get; set; }
        public virtual DbSet<tb_payment> tb_payment { get; set; }
        public virtual DbSet<tb_pengembalian> tb_pengembalian { get; set; }
    }
}
