//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PakMua
{
    using System;
    using System.Web;
    using System.Collections.Generic;
    
    public partial class tb_mobil
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_mobil()
        {
            this.tb_order_mobil = new HashSet<tb_order_mobil>();
        }
    
        public int id_mobil { get; set; }
        public string nama { get; set; }
        public string merk { get; set; }
        public string model { get; set; }
        public string varian { get; set; }
        public Nullable<int> mesin { get; set; }
        public Nullable<int> tenaga { get; set; }
        public Nullable<int> tempat_duduk { get; set; }
        public string transmisi { get; set; }
        public string ac { get; set; }
        public Nullable<decimal> harga_sewa { get; set; }
        public string deskripsi { get; set; }
        public string foto { get; set; }
        public string status { get; set; }
        public Nullable<int> stok { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_order_mobil> tb_order_mobil { get; set; }
    }
}
