//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PakMua
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_order()
        {
            this.tb_order_mobil = new HashSet<tb_order_mobil>();
            this.tb_payment = new HashSet<tb_payment>();
            this.tb_pengembalian = new HashSet<tb_pengembalian>();
        }
    
        public int id_order { get; set; }
        public string no_invoice { get; set; }
        public Nullable<System.DateTime> tgl_order { get; set; }
        public Nullable<System.DateTime> ambil { get; set; }
        public Nullable<System.DateTime> kembali { get; set; }
        public Nullable<int> jumlah_hari { get; set; }
        public Nullable<int> jumlah_mobil { get; set; }
        public Nullable<decimal> total_harga { get; set; }
        public Nullable<int> id_member { get; set; }
        public string status { get; set; }
    
        public virtual tb_member tb_member { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_order_mobil> tb_order_mobil { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_payment> tb_payment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_pengembalian> tb_pengembalian { get; set; }
    }
}
