//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PakMua
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_order_mobil
    {
        public int id_order_mobil { get; set; }
        public Nullable<int> id_mobil { get; set; }
        public Nullable<int> id_order { get; set; }
        public Nullable<System.DateTime> tgl { get; set; }
        public Nullable<int> jumlah { get; set; }
    
        public virtual tb_mobil tb_mobil { get; set; }
        public virtual tb_order tb_order { get; set; }
    }
}
