//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PakMua
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_payment
    {
        public int id_payment { get; set; }
        public string nama { get; set; }
        public string nama_bank { get; set; }
        public string no_rekening { get; set; }
        public Nullable<decimal> transfer { get; set; }
        public Nullable<int> id_order { get; set; }
    
        public virtual tb_order tb_order { get; set; }
    }
}
